# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert list of matrices (alignments) to a 3D array
#'
#' @param input A list of matrices.
#' @param dim A vector of dimensions of 3D array.
#' @export
list_to_array <- function(input, dim) {
    .Call(`_popgencnn_list_to_array`, input, dim)
}

